### ISSUE TITLE
Problem with compile the extension modules

### ISSUE THREAD

**Issue by 1341828568** [FVPLab/Argus-3D#1]
Thank you for the great work!
when i run
 `python setup.py build_ext --inplace`
it comes with
'ValueError: 'src/utils/libmcubes/mcubes.pyx' doesn't match any files'
i don't see libmcubes file in the github project~

**Comment by 1341828568** [comment]
I found libmcubes from other project, but it still missing something like:
'ValueError: 'src/utils/libmesh/triangle_hash.pyx' doesn't match any files'

**Comment by AImind** [comment]
Sorry for missing out on some of the files. They have now been upload
