### ISSUE TITLE
Please ask for Argus-3D configuration information

### ISSUE THREAD

**Issue by JiqiangHuang** [FVPLab/Argus-3D#11]
I would like to ask about the step of compiling the extension module python setup.py build_ext --inplace. The error is as follows:

  File "/home/hjq/anaconda3/envs/argus-3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Is my server environment configured incorrectly?

**Comment by AImind** [comment]
Hi @JiQiangHuang, thanks a lot for your interest on our project. Could you provide detailed hardware information and dependencies? You can also refer to this link first [https://github.com/autonomousvision/occupancy_networks/issues/96#issuecomment-818522473](https://github.com/autonomousvision/occupancy_networks/issues/96#issuecomment-818522473)
[https://github.com/autonomousvision/convolutional_occupancy_networks/issues/33#issue-985264165](https://github.com/autonomousvision/convolutional_occupancy_networks/issues/33#issue-985264165)
