### ISSUE TITLE
Could you release the dataset (i.e., groundtruth occupancies)

### ISSUE THREAD

**Issue by yizhiwang96** [FVPLab/Argus-3D#2]
Such a nice work! Thank you for sharing the code.
I wonder if the training dataset (especially the gt occupancies and watertight meshes) could be released. This will be beneficial for the whole community of 3D generation. Thank you!

**Comment by AImind** [comment]
This portion of files is very large and located on our internal server, which makes it challenging to share. We may share it later, but it might take a considerable amount of time.😔

**Comment by pyh007** [comment]
请问下我生成的怎么全是一样的正方体（Stage2_0_3001.obj这样的obj文件），而没有chair

**Comment by AImind** [comment]
Please check if you have correctly loaded the ckpt file.

**Comment by AImind** [comment]
> Such a nice work! Thank you for sharing the code.
> I wonder if the training dataset (especially the gt occupancies and watertight meshes) could be released. This will be beneficial for the whole community of 3D generation. Thank you!

Hi Wang,
We've uploaded the dataset to HuggingFace. You can download it from [https://huggingface.co/datasets/BAAI/Objaverse-MIX](https://huggingface.co/datasets/BAAI/Objaverse-MIX)
