### ISSUE TITLE
Can this run on Windows?

### ISSUE THREAD

**Issue by Dragonkingpan** [FVPLab/Argus-3D#3]
A very outstanding work. Can this run on Windows? When I execute commands on Windows, the system prompts:
`ResolvePackageNotFound:
  - ld_impl_linux-64=2.38
  - libgomp=11.2.0
  - libgcc-ng=11.2.0
  - nspr=4.35
  - nss=3.89.1
  - libgfortran-ng=11.2.0
  - ncurses=6.4
  - readline=8.2
  - dbus=1.13.18
  - gst-plugins-base=1.14.1
  - gmp=6.2.1
  - libxkbcommon=1.0.1
  - nettle=3.6
  - libedit=3.1.20221030
  - libgfortran5=11.2.0
  - gnutls=3.6.13
  - libstdcxx-ng=11.2.0
  - gstreamer=1.14.1
  - libuuid=1.41.5
  - openh264=2.1.1
  - _openmp_mutex=5.1`

**Comment by AImind** [comment]
I'm sorry, but the program currently only supports Linux systems.
